# Auto-generated by Visual IoT Flow Builder
import time
import requests
from urllib.parse import urlencode
from requests.exceptions import RequestException

API_BASE = 'https://iot.alsabid.com/api'
DEVICES_PATH = 'devices'
REQUEST_TIMEOUT = 6
POLL_SECONDS = 0.1
RETRY_ATTEMPTS = 3
RETRY_BACKOFF = 0.25

def api_request(method, path, payload=None):
    url = f"{API_BASE}/{path}"
    last_exc = None
    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            response = requests.request(
                method,
                url,
                json=payload,
                timeout=REQUEST_TIMEOUT,
                headers={
                    'Connection': 'close',
                    'User-Agent': 'iot-block-script/1.0',
                    'Accept': 'application/json',
                },
            )
            response.raise_for_status()
            return response
        except RequestException as exc:
            last_exc = exc
            if attempt < RETRY_ATTEMPTS:
                time.sleep(RETRY_BACKOFF * (2 ** (attempt - 1)))

    print(f"[api] {method} {url} failed after {RETRY_ATTEMPTS} attempts: {last_exc}")
    return None

def api_get_device(device_id):
    response = api_request("GET", device_id)
    if response is None:
        return {}

    payload = response.json()
    if isinstance(payload, dict):
        return payload
    return {}

def api_get_devices_map():
    response = api_request("GET", DEVICES_PATH)
    if response is None:
        return {}

    payload = response.json()
    devices = payload.get("devices", []) if isinstance(payload, dict) else []
    if not isinstance(devices, list):
        return {}
    return {item.get("deviceId"): item for item in devices if isinstance(item, dict) and item.get("deviceId")}

def api_set_device(device_id, payload):
    response = api_request("POST", f"{device_id}/set", payload)
    if response is not None:
        return True

    def serialize_query_value(value):
        if isinstance(value, bool):
            return int(value)
        return value

    query = urlencode({key: serialize_query_value(value) for key, value in payload.items()})
    fallback_path = f"{device_id}/set?{query}"
    fallback_response = api_request("GET", fallback_path)
    return fallback_response is not None

def read_signal(devices_map, device_id, signal):
    data = devices_map.get(device_id, {})
    if not isinstance(data, dict):
        return None
    return data.get(signal)

last_written = {}

def write_signal(device_id, signal, value):
    key = f"{device_id}:{signal}"
    if key in last_written and last_written[key] == value:
        return
    if api_set_device(device_id, {signal: value}):
        last_written[key] = value

def run():
    while True:
        try:
            devices_map = api_get_devices_map()
            button_101_value = read_signal(devices_map, 'iot-block-001', 'button')
            if bool(button_101_value) == True:
                write_signal('iot-block-001', 'led', True)
            else:
                write_signal('iot-block-001', 'led', False)
        except Exception as exc:
            print(f"[run] unexpected error: {exc}")
        time.sleep(POLL_SECONDS)

if __name__ == '__main__':
    run()